# Room (KMP) - constructor generated by KSP is looked up reflectively
-keep class * extends androidx.room.RoomDatabase { <init>(); }
-dontwarn androidx.room.paging.**

# Kotlinx serialization / coroutines
-dontwarn kotlinx.coroutines.debug.**
-assumenosideeffects class kotlin.jvm.internal.Intrinsics {
    static void checkNotNull(...);
    static void checkNotNullParameter(...);
    static void checkExpressionValueIsNotNull(...);
    static void checkNotNullExpressionValue(...);
    static void checkReturnedValueIsNotNull(...);
    static void checkFieldIsNotNull(...);
    static void checkParameterIsNotNull(...);
}

# Strip Napier debug logging in release
-assumenosideeffects class android.util.Log {
    public static int v(...);
    public static int d(...);
}

# Compose resources are looked up by path, keep them
-keepclassmembers class **.generated.resources.** { *; }
-dontwarn org.jetbrains.compose.resources.**

# Aggressive optimisation
-repackageclasses ''
-allowaccessmodification
-optimizationpasses 5
