build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

complexity:
  active: true
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 4

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    active: false

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false
